class Objectpage_datas_Xykh:


    index_loc = '//a[text()="登录"]'
    dl_anniu = '//span[text()="密码登录"]'
    user_loc = '//input[@name="tel"]'
    password_loc = '//input[@name="pwd"]'
    yzm_loc = '//input[@name="gvcvalue"]'
    login_button_loc = '/html/body/modal-container/div/div/app-registered-login/div/div[3]/form/button'

    xykh_an = '//ul[@class="nav-line col-xs-7 row"]/child::li[5]/child::a'
    sy_zdcx_an = '//ul[@class="index_nav_menu"]/child::li[1]/child::span'        # 首页账单查询
    wdzh_an = '//a[text()="我的账户"]'
    zdcx_an = '//li[@class="active"]/child::span'
    cx_an = '//button[@class="btn_red data-red"]'
    hbzf_an = '//ul[@class="tb-list-top-right"]/child::li[1]'
    ll_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[6]/child::button[1]' # 浏览
    xz_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[6]/child::button[2]' # 下载
    zf_an = '//button[@class="btn_red red-btn"]' # 支付

    ckxq_an = '//div[@class="center-content-div"]/child::div'
    cx_an2 = '//div[@class="btn_red"]'
    xzwj_an = '//ul[@class="tb-list-top-right"]/child::li[2]'
    dcexcel_an = '//ul[@class="tb-list-top-right"]/child::li[3]'
    ydh_an = '//span[@class="input-now position_relative"]/child::input'
    cplx_an = '//span[@class="input-now"]/child::select'
    fjrq_an1 = '//input[@id="browse1"]'
    today_an = '//td[@class="day today active"]'
    fjrq_an2 = '//input[@id="browse2"]'
    xzwj_an2 = '//ul[@class="tb-list-top-right"]/child::li[1]'
    dcexcel_an2 = '//ul[@class="tb-list-top-right"]/child::li[2]'
    fhzdcx_an = '//div[@class="nav-line"]/child::span[2]/child::span[@class="title"]'
    cx_an3 = '//ul[@class="input-information"]/child::div'

    lszd_an = '//div[@class="inquire-left"]/child::ul/child::li[2]'
    wjzkj_an = '//div[@class="inquire-left"]/child::ul/child::li[3]'

    tqcxm_an = '//div[@class="inquire-right"]/child::ul/child::li[1]'
    zddz_an = '//div[@class="inquire-right"]/child::ul/child::li[2]'
    xzlb_an = '//div[@class="inquire-right"]/child::ul/child::li[3]'
    tj_an = '//div[@class="append-element"]/child::button'
    qx_an = '//div[@class="affirm"]/child::button[1]'
    qd_an = '//div[@class="affirm"]/child::button[2]'
    zh_an = '//div[@class="text-input"]/child::li/child::select'
    zdlx_an = '//div[@class="text-input"]/child::li[3]/child::select'
    sjryx_an = '//div[@class="text-input"]/child::li[4]/child::input'
    xg_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr/child::td/child::button[@class="yellow-btn yell"]'
    sc_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr/child::td/child::button[@class="gray-btn yell"]'
    fsjl_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[6]/button[1]'
    yyfs_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[6]/button[2]'
    sryx_an = '//div[@class="div_input"]/child::input'

    xz_an1 = '//span[@class="mc_title-shut"]'
    yx_an2 = '//div[@class="div_input"]/child::input'
    qx_an1 = '//div[@class="button"]/child::button[1]'
    qd_an2 = '//div[@class="button"]/child::button[2]'
    fhzdcx_an1 = '//div[@class="nav-line"]/child::span[2]/child::span'

    sxfp_an = '//div[@class="left-menu"]/child::ul/child::li[2]/child::span' # 赊销发票
    zf_an2 = '//td[@style="border-right: none;"]/child::button[1]'
    sx_an = '//td[@style="border-right: none;"]/child::button[2]'
    xzfp_an = '//td[@style="border-right: none;"]/child::button[3]'
    bywl_an = '//div[@class="left-menu"]/child::ul/child::li[3]/child::span'
    mc_an = '//div[@class="col-xs-3 width_43"]/child::select'
    zj_an = '//div[@class="col-xs-3 width_25"]/child::b[2]'
    js_an = '//div[@class="col-xs-3 width_25"]/child::b[1]'
    sc_an1 = '//div[@class="col-xs-1 float_r"]/child::span'
    tjwlxx_an = '//div[@class="add_query"]'
    cz_an = '//div[@class="baohan-foot-btn-div"]/child::button[1]'
    tjsq_an = '//div[@class="baohan-foot-btn-div"]/child::button[2]'
    ej_qx_an = '//div[@class="btn-div_cancel"]/child::button[1]'
    ej_qd_an = '//div[@class="btn-div_cancel"]/child::button[2]'
    sc_an2 = '//div[@class="col-xs-1 float_r"]/child::span'

    zhgl_an = '//div[@class="left-menu"]/child::ul/child::li[4]/child::span'
    qxsp_an = '//div[@class="btn-line"]/child::button[1]'
    qsrsjhyhm_an = '//div[@class="search-line"]/child::input'
    xzzh_an = '//div[@class="search-line"]/child::select[1]'
    xzsqzt_an = '//div[@class="search-line"]/child::select[2]'
    xzsqqx_an = '//div[@class="search-line"]/child::select[3]'
    qxspcx_an = '//div[@class="search-line"]/child::button'
    qxspck_an = '//div[@class="table-div scroll-bar"]/child::table/child::tbody/child::tr[2]/child::td[7]/child::button'
    gb_an = '//div[@class="btn-div"]/child::button'

    fhzhgl_an = '//div[@class="nav-line"]/child::span[2]/child::span'
    yhgl_an1 = '//div[@class="btn-line"]/child::button[2]'
    yhgl_cx_an = '//button[@class="btn_red btn_red_big right_mar"]'
    yhgl_xzyh_an = '//button[@class="yellow-btn btn_red_big"]'
    yhsjh_an = '//div[@class="input-line"]/child::input[@class="ng-pristine ng-valid ng-touched"]'
    qrsjh_an = '//div[@class="input-line"]/child::input[@class="ng-untouched ng-pristine ng-valid"]'
    qx_an3 = '//div[@class="foot-btn-line"]/child::button[1]'
    qdtj_an = '//div[@class="foot-btn-line"]/child::button[2]'
    ggqx_an = '//table[@class="result-panel-table-auto"]/child::tbody/tr[2]/child::td[5]/child::button[1]'
    sc_an3 = '//table[@class="result-panel-table-auto"]/child::tbody/tr[2]/child::td[5]/child::button[2]'
    ej_qx_an1 = '//div[@class="btn-div-center"]/child::button[1]'
    ej_qrxg_an = '//div[@class="btn-div-center"]/child::button[2]'

    qxbd_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[3]/child::button[1]'
    yyqjaqjz_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[3]/child::button[2]'
    yydz_an = '//table[@class="result-panel-table-auto"]/child::tbody/child::tr[2]/child::td[3]/child::button[3]'
    # 通知设置，发票信息，发票接收人，申请权限 懒得写
    # 待验证 审核记录 懒得写了

    bdzh_an = '//div[@class="left-menu"]/child::ul/child::li[5]/child::span'
    bdzh_input_an = '//span[@class="notNullFlag gray-666"]/following-sibling::input'
    qxbangd_an = '//div[@class="foot_btn"]/child::button[1]'
    wcbd_an = '//div[@class="foot_btn"]/child::button[2]'
    ejqr_qx_an = '//div[@class="btn-div"]/child::button[1]'
    ejqr_qd_an = '//div[@class="btn-div"]/child::button[2]'

    kszh_an = '//div[@class="left-menu"]/child::ul/child::li[6]/child::span'
    djcc_an = '//a[@class="link-a"]'
    yb_an = '//span[@class="right"]/child::input[@name="postCode"]'
    szdq1_an = '//span[@class="right"]/child::select[1]'
    szdq2_an = '//span[@class="right"]/child::select[2]'
    ywxxdz_an = '//span[@class="right"]/child::input[@name="englishAddress"]'
    ywxm_an = '//span[@class="right"]/child::input[@name="englishName"]'
    ywsjh_an = '//span[@class="right"]/child::input[@name="tel"]'
    ywyx_an = '//span[@class="right"]/child::input[@name="email"]'
    ywgsm_an = '//span[@class="right"]/child::input[@name="englishCompanyName"]'
    sqks_an = '//div[@class="btn-line"]/child::button'

    yhxx_an = '//div[@class="left-menu"]/child::ul/child::li[7]/child::span'
    khjlly_an = '//div[@class="left-menu"]/child::ul/child::li[8]/child::span'
